# Generated by Django 3.1.7 on 2021-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, upload_to='images/')),
                ('enroll_number', models.IntegerField()),
                ('gender', models.CharField(max_length=60)),
                ('hobbies', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
